name: Build and Push Multi-Platform Docker Image

on:
  push:

env:
  PLATFORMS: linux/amd64,linux/arm64

jobs:
  prepare-variables:
    runs-on: ubuntu-latest
    steps:
      - id: tag_build_number
        run: echo "tag=$(echo ${{github.ref_name}} | tr -cs 'a-zA-Z0-9' '-')$(date +'%Y%m%d%H%M%S')-${{ github.run_number }}" >> $GITHUB_OUTPUT
      - id: tag_snapshot
        run: echo "tag=$(echo ${{github.ref_name}} | tr -cs 'a-zA-Z0-9' '-')snapshot" >> $GITHUB_OUTPUT
    outputs:
      tag_build_number: ${{ steps.tag_build_number.outputs.tag }}
      tag_snapshot: ${{ steps.tag_snapshot.outputs.tag }}
  build-and-push:
    runs-on: ubuntu-latest
    needs: prepare-variables
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and load test core-image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: |
            ghcr.io/netcracker/qubership/core-base:test
          file: Dockerfile.base-alpine
          platforms: linux/amd64

      - name: Build and load test java-image
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: |
            ghcr.io/netcracker/qubership/java-base:test
          file: Dockerfile.java-alpine
          platforms: linux/amd64

      - name: Prepare test resources
        run: |
          openssl genpkey -algorithm RSA -out testcert_key.pem -pkeyopt rsa_keygen_bits:2048
          openssl req -x509 -newkey rsa:2048 -keyout testcert_key.pem -out testcert.pem -days 365 -nodes -subj "/CN=testcerts.com"
          mkdir certs
          mv testcert.pem certs/

      - name: Validate Truststore
        run: |
          docker run -v ./certs/:/tmp/cert/ -e CERTIFICATE_FILE_PASSWORD=testit --rm ghcr.io/netcracker/qubership/java-base:test \
            keytool -v -list -keystore /etc/ssl/certs/java/cacerts -storepass testit -alias testcert.pem

      - name: Validate ca certificates were copied to store
        run: |
          docker run -v ./certs/:/tmp/cert/ --rm ghcr.io/netcracker/qubership/core-base:test ls -l /etc/ssl/certs/*testcert* 


      - name: Build and push java-image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: |
            ghcr.io/netcracker/qubership/java-base:${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership/java-base:${{ needs.prepare-variables.outputs.tag_build_number }}
          file: Dockerfile.java-alpine
          platforms: ${{ env.PLATFORMS }}

      - name: Build and push core-image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.actor != 'dependabot[bot]' }}
          tags: |
            ghcr.io/netcracker/qubership/core-base:${{ needs.prepare-variables.outputs.tag_snapshot }}
            ghcr.io/netcracker/qubership/core-base:${{ needs.prepare-variables.outputs.tag_build_number }}
          file: Dockerfile.base-alpine
          platforms: ${{ env.PLATFORMS }}
